# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Mon, 28 Dec 2020 00:30:27 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$ER9LE4v0lAU6s4fspLjHDekI7RNbsDq6qEX4wpzyFRevnKAA4GafK:admin:admin@gmail.com:admin,user
